# 服务端口
server:
  port: 8202
# 服务名

spring:
  application:
    name: common-service
  # 设置环境dev、test、prod
  profiles:
    active: dev
  # 数据连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hospital_common?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: root1234
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    redis
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        # 最大阻塞等待时间,负数表示没有限制
        max-idle: 5
        min-idle: 0